"""Regeneration as one decision (CR 701.19).

Two shapes of the same replacement, and until now only one of them existed:

* **A shield** — "Regenerate target creature" (Death Ward), "{B}: Regenerate
  this creature" — is CR 701.19a: an effect a resolving spell or ability
  creates, good for *the next* destruction this turn. It is stored as
  ``Permanent.regeneration_shield``.
* **A static ability** — "If this creature would be destroyed, regenerate it."
  (Clergy of the Holy Nimbus) — is CR 701.19b, and the rule is explicit that it
  applies "**each time** that permanent would be destroyed". There is no shield
  to spend and no count to keep: the permanent's own text is the effect, so it
  is derived on every destruction the way every other continuous effect in this
  engine is derived.

Both are the same *decision* at the same moment — "is this destruction replaced,
and by what?" — so both are answered here, once. They were not: the shield check
was written out at the two destruction paths (``mixins/effects._do_destroy`` and
``mixins/helpers._destroy_swept_permanents``), and the two copies had already
drifted — one removed the marked damage CR 701.19a-b require and the other left
it, so a creature regenerated by a state-based sweep kept its lethal damage
unless the caller happened to pass an ``on_regenerate`` callback that cleared
it. That is the shape this file removes: a second destruction path added later
would have been a third copy, and adding the static form to two copies would
have been two chances to forget it.

**The rider is read here too.** "This creature can't be regenerated this turn"
(CR 701.19c) does not stop a shield being *created* — it stops one being
*applied* — and it has to stop the static form the same way, because on Clergy
of the Holy Nimbus the rider and the static regeneration are printed on the same
card and the rider is the whole point of the second line. A rider that only
knew about shields would leave that ability doing nothing at all.
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING

if TYPE_CHECKING:  # pragma: no cover - typing only
    from .game import Game
    from .models import Permanent

#: The permanent-name half of the printed template. A card names itself by type
#: in modern oracle text ("this creature"); the noun is payload, so a Regenerating
#: artifact or land printed with the same sentence is read by the same row.
_SELF_NOUN = r"(?:creature|permanent|artifact|land|enchantment)"

#: "If this creature would be destroyed, regenerate it." Anchored at both ends,
#: because a *conditional* version ("If this creature would be destroyed during
#: your turn, …") is a different effect and must keep refusing rather than being
#: admitted by a prefix and then regenerating unconditionally.
_SELF_REGENERATION = re.compile(
    rf"^if this {_SELF_NOUN} would be destroyed, regenerate it$"
)

#: The metadata key both destruction paths already set (Disintegrate, Hurr
#: Jackal, and Clergy's own second ability). Named once so the rider and the
#: things that raise it cannot disagree about the spelling.
CANT_BE_REGENERATED = "cant_be_regenerated_this_turn"

#: How many times this permanent has regenerated this turn.
#:
#: "At the beginning of each end step, **if this creature regenerated this
#: turn**, create a 0/1 blue Starfish creature token **for each time it
#: regenerated this turn**." (Spiny Starfish.) A count rather than a flag,
#: because the card asks for both readings of the same record and a boolean
#: would answer the second one "1" however many shields were spent.
#:
#: Written in :func:`_apply` and nowhere else — that function is already the one
#: place a regeneration happens, static form and shield alike, so a count kept
#: at the two destruction paths would be the split this module was written to
#: remove. Swept with the turn by ``mixins/_constants._EOT_METADATA_KEYS``,
#: which runs at cleanup (CR 514.2) and therefore *after* the end step that
#: reads it.
REGENERATED_THIS_TURN = "regenerated_this_turn"

#: "Creatures dealt damage by this creature this turn can't be regenerated this
#: turn." (Bone Shaman grants it; Runesword's *targeted* wording is the same
#: rule stated as a one-shot.) CR 701.19c seen from the dealer's end: it is a
#: standing property of the damager rather than a rider on one event, so it is
#: derived from the permanent's text at the damage seam exactly as the static
#: regeneration above is derived at the destruction paths.
#:
#: The noun is payload for the reason it is one row up, and the whole sentence
#: is anchored: a narrower printing ("creatures dealt damage by this creature
#: **during your turn**") would be a different rule and must keep refusing.
_DENIES_REGENERATION = re.compile(
    rf"^creatures dealt damage by this {_SELF_NOUN} this turn "
    r"can't be regenerated this turn$"
)


def _normalized_line(line: str) -> str:
    """One printed line as these patterns read it: no reminder text, no case,
    no trailing full stop."""
    return re.sub(r"\([^)]*\)", "", line or "").strip().lower().rstrip(".").strip()


def denies_regeneration_line(line: str) -> bool:
    """Whether one printed line is, in full, the dealer-side rider above.

    Read by the support gate and by the grammar's parse claim, like its
    neighbour — and by ``engine/granted_abilities.py``'s probe through both,
    which is what lets Bone Shaman grant the sentence at all.
    """
    return bool(_DENIES_REGENERATION.match(_normalized_line(line)))


def denies_regeneration(permanent: "Permanent") -> bool:
    """Whether damage *permanent* deals leaves its victim unregenerable.

    ``effective_card`` rather than ``card``, for the reason
    :func:`regenerates_itself` gives: the sentence arrives on Bone Shaman as a
    layer-6 grant and is folded in there, so a reader of the printed text would
    see nothing at all.
    """
    return any(
        denies_regeneration_line(line)
        for line in (permanent.effective_card.oracle_text or "").splitlines()
    )


def self_regeneration_line(line: str) -> bool:
    """Whether one printed line is, in full, the CR 701.19b static above.

    Read by ``engine/oracle.py``'s support gate and by the grammar's parse
    claim, so what this file implements and what a card is admitted for are the
    same sentence. Without it, a creature whose only non-keyword line is this
    one produces no instruction and would report unsupported however well the
    replacement worked.
    """
    return bool(_SELF_REGENERATION.match(_normalized_line(line)))


def regenerates_itself(permanent: "Permanent") -> bool:
    """Whether *permanent* carries the static above.

    Read off ``effective_card`` rather than ``card``: a Clone of the Clergy has
    the ability (CR 707.2) and a permanent that has lost all abilities does not.
    """
    return any(
        self_regeneration_line(line)
        for line in (permanent.effective_card.oracle_text or "").splitlines()
    )


def cant_be_regenerated(permanent: "Permanent") -> bool:
    """CR 701.19c: the rider that makes any regeneration inert this turn."""
    return bool(permanent.metadata.get(CANT_BE_REGENERATED))


def regeneration_replaces_destruction(game: "Game", permanent: "Permanent") -> bool:
    """Replace *permanent*'s destruction with a regeneration, if one applies.

    Returns whether the destruction was replaced. When it was, the permanent has
    been tapped and its marked damage removed (CR 701.19a-b) and the caller must
    not put it into a graveyard.

    The static form is preferred over a shield when both apply. Both are
    replacement effects and CR 616.1 gives the choice to the affected
    permanent's controller, and no controller would spend a one-shot shield
    while an unlimited static is available — so the choice is made rather than
    prompted, and the shield is left on the permanent for a later destruction
    this turn.
    """
    if cant_be_regenerated(permanent):
        return False
    if regenerates_itself(permanent):
        _apply(game, permanent, f"{permanent.card.name} regenerates itself (701.19b)")
        return True
    if permanent.regeneration_shield > 0:
        permanent.regeneration_shield -= 1
        _apply(game, permanent, f"{permanent.card.name} regenerated")
        return True
    return False


def _apply(game: "Game", permanent: "Permanent", message: str) -> None:
    """CR 701.19a-b's alternate effect: tap it and remove all damage marked on
    it.

    The "remove it from combat" half of the rule is not carried out here; it was
    absent from both destruction paths before they were consolidated, and adding
    it is a combat-map change rather than a regeneration one.
    """
    game.become_tapped(permanent)
    permanent.damage_marked = 0
    permanent.metadata.pop("received_deathtouch", None)
    permanent.metadata[REGENERATED_THIS_TURN] = (
        int(permanent.metadata.get(REGENERATED_THIS_TURN, 0)) + 1
    )
    game.log.append(message)


__all__ = [
    "CANT_BE_REGENERATED",
    "REGENERATED_THIS_TURN",
    "cant_be_regenerated",
    "regeneration_replaces_destruction",
    "regenerates_itself",
    "self_regeneration_line",
]
