"""Generate BEHAVIOUR_CLASSES.md — the behavioural-equivalence tracker.

Cards that run the same engine paths are grouped into one class (see
engine/behaviour_signature.py). A card whose class already contains a verified
card needs no separate manual pass, so this is how card verification scales past
the point where checking every card by hand is possible.

The classes are snapshotted to behaviour_classes_snapshot.json and guarded by
tests/engine/test_behaviour_classes.py. That ratchet exists because the
signature's failure mode is silent: if it stops distinguishing two behaviours,
coverage *rises* and nothing looks wrong. An earlier signature declared Flight
equivalent to Control Magic. Review every new merge before accepting it.

Usage:
    python scripts/behaviour_classes.py            # rewrite the tracker
    python scripts/behaviour_classes.py --check    # exit 1 if classes drifted
    python scripts/behaviour_classes.py --accept   # re-snapshot after review
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts"))
sys.path.insert(0, str(REPO_ROOT))

from engine.behaviour_signature import behaviour_classes  # noqa: E402
from engine.card_loader import load_catalog, load_cards  # noqa: E402
from set_argument import add_set_argument, resolve_set  # noqa: E402

SNAPSHOT_PATH = Path(__file__).resolve().parent / "behaviour_classes_snapshot.json"
OUTPUT_PATH = REPO_ROOT / "BEHAVIOUR_CLASSES.md"
VERIFICATION_PATH = REPO_ROOT / "card_verification.json"


def current_classes() -> list[list[str]]:
    """Multi-member classes only, in a stable order (largest first, then name)."""
    groups = behaviour_classes(load_catalog())
    multi = [names for names in groups.values() if len(names) > 1]
    return sorted(multi, key=lambda names: (-len(names), names[0]))


def load_snapshot() -> list[list[str]]:
    if not SNAPSHOT_PATH.exists():
        return []
    return [list(entry) for entry in json.loads(SNAPSHOT_PATH.read_text(encoding="utf-8"))]


def diff(current: list[list[str]], snapshot: list[list[str]]) -> tuple[list, list]:
    current_sets = {frozenset(c) for c in current}
    snapshot_sets = {frozenset(c) for c in snapshot}
    added = sorted((sorted(s) for s in current_sets - snapshot_sets), key=lambda n: n[0])
    removed = sorted((sorted(s) for s in snapshot_sets - current_sets), key=lambda n: n[0])
    return added, removed


def _verified_names() -> set[str]:
    if not VERIFICATION_PATH.exists():
        return set()
    results = json.loads(VERIFICATION_PATH.read_text(encoding="utf-8")).get("results", {})
    return {name for name, entry in results.items() if entry.get("status") == "pass"}


def render_markdown(classes: list[list[str]]) -> str:
    catalog = load_catalog()
    verified = _verified_names()
    covered = sum(1 for names in classes for n in names if n not in verified and any(p in verified for p in names))
    grouped = sum(len(names) for names in classes)
    lines = [
        "# Behavioural Equivalence Classes",
        "",
        "Cards the engine resolves through the same code paths, differing only in "
        "values it handles generically (amounts, which colour, power/toughness). "
        "Generated by `scripts/behaviour_classes.py` — do not edit by hand.",
        "",
        "A card whose class contains a **verified** card needs no separate manual "
        "pass: it exercises no engine path that card didn't. This is weaker than "
        "checking the card — it inherits its peer's correctness, and cannot catch "
        "a card whose data breaks a generic path.",
        "",
        f"- Cards in the catalog: **{len(catalog)}**",
        f"- Distinct behaviours: **{len(behaviour_classes(catalog))}**",
        f"- Cards sharing a behaviour with another: **{grouped}** in **{len(classes)}** classes",
        f"- Unverified cards covered by a verified peer: **{covered}**",
        "",
        "| Size | Cards |",
        "| --- | --- |",
    ]
    for names in classes:
        shown = ", ".join(
            f"**{n}**" if n in verified else n for n in names
        )
        lines.append(f"| {len(names)} | {shown} |")
    lines += ["", "Bold = manually verified; the rest of that row is covered by it.", ""]
    return "\n".join(lines)


def write_markdown(classes: list[list[str]]) -> None:
    OUTPUT_PATH.write_text(render_markdown(classes), encoding="utf-8")


def _resolve_scope(parser, args):
    """The ``--set`` contract for a whole-pool instrument (see
    grammar_coverage.py): a specific ``--set CODE`` is a stdout-only report,
    never a write of the committed .md and never a ratchet move; ``--all`` and
    ``--cards`` are refused because the default already reads both manifest
    roles and a path outside the manifest has no row here."""
    if args.whole_pool:
        parser.error(
            "--all is this instrument's default behaviour (it always reads "
            "both manifest roles); use --set CODE to scope the report"
        )
    if args.cards_path:
        parser.error(
            "this instrument's analysis is keyed by manifest sets; "
            "use --set CODE"
        )
    if args.set_code is None:
        return None
    for flag in ("check", "accept", "accept_probe"):
        if getattr(args, flag, False):
            parser.error(
                f"--set is a stdout-only report; --{flag.replace('_', '-')} "
                "always covers the whole pool"
            )
    return resolve_set(parser, args)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 if classes drifted")
    parser.add_argument("--accept", action="store_true", help="re-snapshot after review")
    add_set_argument(parser, default=None)
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    selection = _resolve_scope(parser, args)

    if selection is not None:
        # The Phase 2 question: which of this set's cards land in an existing
        # class? Classes are computed over the shipped catalog plus the
        # selection (deduped by name), so a measured set's card can join a
        # shipped card's class before anyone implements it.
        catalog = {card.name: card for card in load_catalog()}
        set_names = set()
        for path in selection.paths:
            for card in load_cards(str(path)):
                set_names.add(card.name)
                catalog.setdefault(card.name, card)
        groups = behaviour_classes(catalog.values())
        multi = [
            names for names in groups.values()
            if len(names) > 1 and any(name in set_names for name in names)
        ]
        multi.sort(key=lambda names: (-len(names), names[0]))
        print(f"Pool: {selection.label}")
        print(
            f"{len(set_names)} cards; {len(multi)} multi-member class(es) "
            "contain at least one of them (* = in this set):"
        )
        for names in multi:
            shown = ", ".join(
                f"*{name}" if name in set_names else name for name in names
            )
            print(f"  [{len(names)}] {shown}")
        return 0

    classes = current_classes()

    if args.accept:
        SNAPSHOT_PATH.write_text(json.dumps(classes, indent=2) + "\n", encoding="utf-8")
        write_markdown(classes)
        print(f"accepted {len(classes)} behaviour class(es) into {SNAPSHOT_PATH.name}")
        return 0

    added, removed = diff(classes, load_snapshot())

    if args.check:
        if added or removed:
            if added:
                print("NEW or CHANGED behaviour classes — review each before accepting.")
                print("A class that gained a member means two cards the engine used to")
                print("treat differently now look identical to the signature:")
                for names in added:
                    print(f"  + {names}")
            if removed:
                print("Behaviour classes that no longer occur:")
                for names in removed:
                    print(f"  - {names}")
            print("\nIf every change is correct: scripts/behaviour_classes.py --accept")
            return 1
        if OUTPUT_PATH.read_text(encoding="utf-8") != render_markdown(classes):
            print(f"FAIL: {OUTPUT_PATH.name} is stale — rerun the script and commit the result")
            return 1
        print(f"OK: {len(classes)} behaviour class(es) unchanged")
        return 0

    write_markdown(classes)
    print(f"Wrote {OUTPUT_PATH.name}: {len(classes)} class(es)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
